### ISSUE TITLE
Notebook and write-up

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/Iterative_summarization#1]
## User story

Work made for the Alignment jam #4 on Mechanistic Interpretability. A first draft of ideas on the subject.

## Acceptance Criterion

* The notebook and the code are documented 
* The write-up corresponds to the code

## Tasks

- [x] Fine-tuning of GPT-2 for summarization
- [x] Rendering using Neel Nanda's toolbox
- [x] Trying to deduce and explain the graphs
- [x] Add the write-up
